//! Raw, unsafe FFI bindings to SUNDIALS generated by bindgen.
//!
//! You should not use this crate directly; prefer the safe `sundials` crate.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
